# https://hub.docker.com/repository/docker/comp1531/automarking/general
image: comp1531/automarking:latest

stages:
  - checks

testing:
  stage: checks
  script:
    # - echo "Uncomment script below once you have updated your package.json"
    - npm install
    - SERVER_LOG=$(mktemp)

    # Start server in background and capture output in temp file
    - npm start &> $SERVER_LOG & pid=$!
    - sleep 2
    - ps -o pid | egrep -q "^\s*${pid}$" || (cat $SERVER_LOG && exit 1)

    # Run test then kill server
    - npm test || (cat $SERVER_LOG && exit 1)
    - sleep 1
    - kill -SIGINT %1

    - cat $SERVER_LOG
  only:
    - master

# TODO: add linting

linting:
  stage: checks
  script:
    - npm install
    - npm run lint
  only:
    - master
